command_timeout = 1250
[directory]
style = "purple"
read_only = " "
truncation_length = 0
truncation_symbol = "repo: "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[cmd_duration]
min_time = 1
format = "took [$duration]($style)"

[character]
success_symbol = "[ 0 ➜](green)"
error_symbol = "[➜](red)"

[status]
format = "[ $status ](red)"
disabled = false
style = "red"

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "󰛥 "

[custom.make]
files = ["Makefile", "makefile"]
format = "via [$symbol v$output ]($style)"
symbol = ""
style = "bold blue"
shell = ["sh", "-c", "make --version | rg '^GNU Make (\\d+\\.\\d+)$' -or '$1'"]
